# See in https://github.com/marketplace/actions/github-labeler?version=v5.1.0
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "Severity/Bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "Severity/Doc"
  color: "0e8a16"
  description: "Improvements or additions to documentation"
- name: "Severity/Feature"
  color: "e4e669"
  description: "Improvements or additions to documentation"
- name: "Severity/Perf"
  color: "fbca04"
  description: "Extra attention is needed for performance"
- name: "Severity/Question"
  color: "1d76db"
  description: "Questions or supporting information is needed"
- name: "Severity/Refactor"
  color: "c2e0c6"
  description: "Refactoring & code improvement"
- name: "wontfix_it"
  color: "ffffff"
  description: "This will not be worked on"
