# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet Package (.NET)

on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
    # Prepare: Enlist + Restore + Build + Test
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release -p:Deterministic=true -p:ContinuousIntegrationBuild=true -v normal --no-restore
    - name: Test
      run: dotnet test -c Release -v normal --no-build

    # Extract Version Tag
    - name: Extract version number
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        if [[ "$VERSION" =~ -pre$ ]]; then
          echo "PACKAGE_SOURCE=https://api.nuget.org/v3/index.json" >> $GITHUB_ENV
        elif [[ "$VERSION" =~ -[a-zA-Z]+$ ]]; then
          echo "PACKAGE_SOURCE=https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" >> $GITHUB_ENV
        else
          echo "PACKAGE_SOURCE=https://api.nuget.org/v3/index.json" >> $GITHUB_ENV
        fi
        
    # Publish NuGet package: Pack + Push
    - name: Pack Nuget package
      run: dotnet pack -c Release --no-build -o ./artifacts -p:PackageVersion=${{ env.VERSION }}
    - name: Push Nuget package
      run: dotnet nuget push ./artifacts/*.nupkg -s ${{ env.PACKAGE_SOURCE }} -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate

    # Publish Playground CLI: Publish + Zip + Release
    - name: Publish Binaries
      run: |
        dotnet publish -c Release -r win-x64
        dotnet publish -c Release -r linux-x64
        dotnet publish -c Release -r osx-arm64
    - name: Archive Binaries
      run: |
        original_dir=$(pwd)
        cd ./publish/win-x64/Flurl.Http.Spec.Playground
        zip -r "$original_dir/artifacts/playground-win.x64-v${{ env.VERSION }}.zip" *
        cd "$original_dir"
        tar -czvf ./artifacts/playground-linux.x64-v${{ env.VERSION }}.tar.gz -C ./publish/linux-x64/Flurl.Http.Spec.Playground .
        tar -czvf ./artifacts/playground-osx-arm64-v${{ env.VERSION }}.tar.gz -C ./publish/osx-arm64/Flurl.Http.Spec.Playground .
    - name: Release Binaries
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ env.VERSION }}
        body: |
          Release notes for version ${{ env.VERSION }}:
          - Playground CLI built and packaged successfully.
        files: |
          ./artifacts/playground-*.zip
          ./artifacts/playground-*.tar.gz 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
